apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spark
  namespace: legalrag
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: spark
    namespace: legalrag
  releaseName: spark
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
#  values:
#    replicaCount: 2