apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spark
spec:
  chartRef:
    kind: OCIRepository
    name: spark
    namespace: flux-system
  interval: 10m
  values:
    replicaCount: 2