apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spark
  namespace: legalrag
spec:
  interval: 5m
  releaseName: spark
  chartRef:
    kind: OCIRepository
    name: spark
    namespace: legalrag
  valuesFrom:
    - kind: ConfigMap
      name: spark-values