apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spark
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: bitnami/spark
      version: 9.2.14
      sourceRef:
        kind: OCIRepository
        name: spark
  values:
    replicaCount: 2