apiVersion: source.toolkit.fluxcd.io/v2
kind: OCIRepository
metadata:
  name: spark
  namespace: legalrag
spec:
  interval: 5m0s
  timeout: 2m0s
  url: oci://registry-1.docker.io/bitnamicharts/spark
  ref:
    semver: ">9.2.0"