apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: spark
  namespace: legalrag
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/spark
  ref:
    semver: ">4.2.0"