---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: spark
  namespace: legalrag
spec:
  interval: 5m0s
  timeout: 2m0s
  url: oci://registry-1.docker.io/bitnamicharts/spark
  ref:
    semver: ">9.2.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spark
  namespace: legalrag
spec:
  interval: 10m0s
  timeout: 2m0s
  chartRef:
    kind: OCIRepository
    name: spark
    namespace: legalrag
  releaseName: spark
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    - kind: ConfigMap
      name: spark-values
      valuesKey: spark-configmap.yaml
