apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: milvus
  namespace: legalrag
spec:
  interval: 5m
  releaseName: milvus
  chartRef:
    kind: OCIRepository
    name: milvus
    namespace: legalrag
  valuesFrom:
    - kind: ConfigMap
      name: milvus-values