apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: milvus
  namespace: legalrag
spec:
  interval: 5m
  timeout: 2m0s
  chartRef:
    kind: OCIRepository
    name: milvus
    namespace: legalrag  
  releaseName: milvus
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled  
  valuesFrom:
    - kind: ConfigMap
      name: milvus-values