apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: milvus
  namespace: legalrag
spec:
  interval: 10m
  chart:
    spec:
      chart: milvus
      version: '4.2.19'
      sourceRef:
        kind: HelmRepository
        name: milvus
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2